### ISSUE TITLE
XCode 9 support?

### ISSUE THREAD

**Issue by hsleedevelop** [funky-monkey/QuickAdd#1]
XCode 9 support?
It isn't showing QuickAdd menu in XCode9

**Comment by funky-monkey** [comment]
That is a good idea. If you want you can pick this up, i'll mark this as #hacktoberfest

**Comment by kaphacius** [comment]
works on my Xcode9

**Comment by tahaburak** [comment]
I'm assuming you tried it with [this release](https://github.com/funky-monkey/QuickAdd/tree/master/release). 

However it should work as intended with these steps:

1. Download and unzip the project.
2. Open "Add Method.xcodeproj".
3. Enable target signing for both the Application and the Source Code Extension.
4. Product > Archive.
5. Right click archive > Show in Finder.
6. Right click archive > Show Package Contents.
7. Open Products, Applications.
8. Drag **Add Method.app** to Applications folder.
9. Run **Add Method.app** and exit.
10. Go to System Preferences -> Extensions -> Xcode Source Editor and enable this extension.
11. The menu-item should now be available from Xcode's Editor menu.
